### ISSUE TITLE
No event is triggered when click in label

### ISSUE THREAD

**Issue by aganglada** [indrimuska/angular-switcher#2]
When I click in the label the change event is not triggered.

Steps to reproduce:
- click in switcher
- event is triggered
- click in label
-  no event is triggered

I think it makes sense to trigger the change event when the label is clicked, because you are setting the state of the switcher.

What do you think?

**Comment by indrimuska** [comment]
Hi @aganglada,
You're right, Switcher have to trigger `onChange` function every time the value updates.
I will fix it asap, thank you for reporting this!

**Comment by aganglada** [comment]
OMG how fast! Did you publish already the new version in npm?

**Comment by indrimuska** [comment]
Check out the release [0.2.3](https://github.com/indrimuska/angular-switcher/releases/tag/0.2.3).
I already publish it on npm network :wink: - https://www.npmjs.com/package/angular-switcher

**Comment by aganglada** [comment]
Thanks dude! Awesome
