### ISSUE TITLE
Grunt build tasks in yeoman do not add css and js from dist dir

### ISSUE THREAD

**Issue by mgpitt** [indrimuska/angular-switcher#4]
Fixed with change to bower.json

from:

`"main": [
    "./js/angular-switcher.js"
  ]`

to:

`"main": [
    "dist/angular-switcher.min.js", 
      "dist/angular-switcher.min.css"
  ]`

**Comment by indrimuska** [comment]
Just released 0.2.6 with this update.
Thank you @mgpitt!

**Comment by mgpitt** [comment]
Awesome!
