### ISSUE TITLE
Switcher line and button position are broken in IE9

### ISSUE THREAD

**Issue by redboul** [indrimuska/angular-switcher#6]
Hi there,

I have integrated  your really nice switcher in a project but display is broken on old version of IE (specifically IE9) because it does support gradient...

in Chrome : 
![image](https://cloud.githubusercontent.com/assets/6637605/16225905/42ad042a-37a9-11e6-8213-b311b6452bc9.png)
in IE9:
![image](https://cloud.githubusercontent.com/assets/6637605/16225916/58dea140-37a9-11e6-8de6-2220e568a771.png)

I have managed to make it work using IE specific CSS but (margin and top modified for button and background-color used for line).

I'm not sure you want to do something about that anyway...

nice work, thanks !

**Comment by indrimuska** [comment]
Hi @redboul, thank you for reporting this.
I'm going to find a way to test the directive with IE9, then I'll get back to you. :)

**Comment by indrimuska** [comment]
As you said, IE9 doesn't support gradients, so I added a background color fallback and upgraded the browser-specific styles (-ms-*) for the position of the line and the button.
You should be able to use Angular Switcher even with IE9 now, thank you @redboul!
