### ISSUE TITLE
Revert the Action

### ISSUE THREAD

**Issue by abCods** [indrimuska/angular-switcher#7]
Is there any way to revert the switch from controller?
I am supposed to show a dialog confirming the switch which is happening. The issue is that it switches anyway if I select either of the options. I need  a way to restrict/ revert the switch.
Thanks!

**Comment by indrimuska** [comment]
Hi @bilalTechverx,
The concept of *Revert* is strictly related to the application context, and means nothing in more general purpose. In your use case revert is the previous value before hitting any submit or confirmation button, but how can I know how many times a user have toggle the value of a switcher?

If the answer is "only one time" then you can just switch back the value you currently have. In all the other cases, if the user haven't changed the switcher value or he has switched it several times then the directive has no way to remember witch was the original value. This could be solved application side from your part.

You need to save the switcher value when the controller loads itself and use it when you want to perform the "Revert" action.

```html
<div ng-controller="myController">
   <switcher ng-model="switcherValue"></switcher>
   <button ng-click="onRevert()"> Revert </button>
</div>
```
```javascript
angular
   .module('MyApp', ['switcher'])
   .controller('myController', ['$scope', function ($scope) {
      var mySwitcherValue = $scope.switcherValue; // init phase
      
      $scope.onRevert = function () {
         var confirmationResult = confirm('Are you sure you want to revert?');
         if (confirmationResult) { // perform revert
            $scope.switcherValue = mySwitcherValue;
         }
      };
   }]);
```

Hope this helps :)
